services:
  postgres:
    image: postgres:16
    container_name: video_platform_search_db
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_streaming_search
    volumes:
      - pgdata:/var/lib/postgresql/searchservicedata

  redis:
    image: redis:7-alpine
    container_name: video-platform-search-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
