services:
  postgres:
    image: postgres:16
    container_name: video_platform_search_db
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_streaming_search
    volumes:
      - pgdata:/var/lib/postgresql/searchservicedata

  search_service:
    image: ${ECR_REGISTRY}/search-service:latest
    container_name: video-platform-search
    restart: unless-stopped
    env_file:
      - .env.search
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
