syntax = "proto3";

package video.metadata.v1;

message GetVideoMetaDataRequest {
  repeated string video_id = 1;
}

message VideoMetaData {
  string video_id = 1;
  string title = 2;
  optional string description = 3;
  string thumb_url = 4;
  int64 view = 5;
  int32 duration = 6;
  int32 date = 7;
  string channel = 8;
  string visibility = 9;
}

message GetVideoMetaDataResponse {
  repeated VideoMetaData video_metadata = 1;
}

service VideoMetaDataService {
  rpc GetVideoMetaData(GetVideoMetaDataRequest) returns (GetVideoMetaDataResponse);
}
